<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PersonalWorkBoard.Server</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="MySqlConnector" />
    <ProjectReference Include="../PersonalWorkBoard.Contracts/PersonalWorkBoard.Contracts.csproj" />
    <ProjectReference Include="../PersonalWorkBoard.Domain/PersonalWorkBoard.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Database/schema.sql" />
  </ItemGroup>
</Project>
